version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  composer:
    image: composer:latest
    volumes:
      - .:/app
    working_dir: /app
    command: composer install

volumes:
  jenkins_home:
